version: "3.8"
name: argon-test
services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: argon-test
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
